config/routes.rb
Rails.application.routes.draw do
  resources :slack_counts

  resources :vk_posts

  resources :tweeets

  get "main/index"
  resources :main
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/tweeet.rb
class Tweeet < ActiveRecord::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy]

  # GET /tweeets
  # GET /tweeets.json
  def index
    @tweeets = Tweeet.all
 
  end

  # GET /tweeets/1
  # GET /tweeets/1.json
  def show

  end

  # GET /tweeets/new
  def new
    
         # MainController.checkNewTweets

    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets
  # POST /tweeets.json
  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1
  # PATCH/PUT /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1
  # DELETE /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweeet_params
      params.require(:tweeet).permit(:tweet_id, :tweet_url, :full_text)
    end
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/tweeets/_form.html.erb
<%= form_for(@tweeet) do |f| %>
  <% if @tweeet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
      <% @tweeet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet_id %><br>
    <%= f.text_field :tweet_id %>
  </div>
  <div class="field">
    <%= f.label :tweet_url %><br>
    <%= f.text_area :tweet_url %>
  </div>
  <div class="field">
    <%= f.label :full_text %><br>
    <%= f.text_area :full_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweeets</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>Tweet url</th>
      <th>Full text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeets.each do |tweeet| %>
      <tr>
        <td><%= tweeet.tweet_id %></td>
        <td><%= tweeet.tweet_url %></td>
        <td><%= tweeet.full_text %></td>
        <td><%= link_to 'Show', tweeet %></td>
        <td><%= link_to 'Edit', edit_tweeet_path(tweeet) %></td>
        <td><%= link_to 'Destroy', tweeet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweeet', new_tweeet_path %>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweeet.tweet_id %>
</p>

<p>
  <strong>Tweet url:</strong>
  <%= @tweeet.tweet_url %>
</p>

<p>
  <strong>Full text:</strong>
  <%= @tweeet.full_text %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>