config/routes.rb
Rails.application.routes.draw do
  resources :slack_counts

  resources :vk_posts

  resources :tweeets

  get "main/index"
  resources :main
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/slack_count.rb
class SlackCount < ActiveRecord::Base
end

app/controllers/slack_counts_controller.rb
class SlackCountsController < ApplicationController
  before_action :set_slack_count, only: [:show, :edit, :update, :destroy]

  # GET /slack_counts
  # GET /slack_counts.json
  def index
    @slack_counts = SlackCount.all
  end

  # GET /slack_counts/1
  # GET /slack_counts/1.json
  def show
  end

  # GET /slack_counts/new
  def new
    @slack_count = SlackCount.new
  end

  # GET /slack_counts/1/edit
  def edit
  end

  # POST /slack_counts
  # POST /slack_counts.json
  def create
    @slack_count = SlackCount.new(slack_count_params)

    respond_to do |format|
      if @slack_count.save
        format.html { redirect_to @slack_count, notice: 'Slack count was successfully created.' }
        format.json { render :show, status: :created, location: @slack_count }
      else
        format.html { render :new }
        format.json { render json: @slack_count.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slack_counts/1
  # PATCH/PUT /slack_counts/1.json
  def update
    respond_to do |format|
      if @slack_count.update(slack_count_params)
        format.html { redirect_to @slack_count, notice: 'Slack count was successfully updated.' }
        format.json { render :show, status: :ok, location: @slack_count }
      else
        format.html { render :edit }
        format.json { render json: @slack_count.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slack_counts/1
  # DELETE /slack_counts/1.json
  def destroy
    @slack_count.destroy
    respond_to do |format|
      format.html { redirect_to slack_counts_url, notice: 'Slack count was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slack_count
      @slack_count = SlackCount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slack_count_params
      params.require(:slack_count).permit(:count)
    end
end

app/helpers/slack_counts_helper.rb
module SlackCountsHelper
end

app/views/slack_counts/_form.html.erb
<%= form_for(@slack_count) do |f| %>
  <% if @slack_count.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slack_count.errors.count, "error") %> prohibited this slack_count from being saved:</h2>

      <ul>
      <% @slack_count.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slack_counts/edit.html.erb
<h1>Editing Slack Count</h1>

<%= render 'form' %>

<%= link_to 'Show', @slack_count %> |
<%= link_to 'Back', slack_counts_path %>

app/views/slack_counts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Slack Counts</h1>

<table>
  <thead>
    <tr>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slack_counts.each do |slack_count| %>
      <tr>
        <td><%= slack_count.count %></td>
        <td><%= link_to 'Show', slack_count %></td>
        <td><%= link_to 'Edit', edit_slack_count_path(slack_count) %></td>
        <td><%= link_to 'Destroy', slack_count, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slack count', new_slack_count_path %>

app/views/slack_counts/new.html.erb
<h1>New Slack Count</h1>

<%= render 'form' %>

<%= link_to 'Back', slack_counts_path %>

app/views/slack_counts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Count:</strong>
  <%= @slack_count.count %>
</p>

<%= link_to 'Edit', edit_slack_count_path(@slack_count) %> |
<%= link_to 'Back', slack_counts_path %>