config/routes.rb
Rails.application.routes.draw do
  resources :slack_counts

  resources :vk_posts

  resources :tweeets

  get "main/index"
  resources :main
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/vk_post.rb
class VkPost < ActiveRecord::Base
end

app/controllers/vk_posts_controller.rb
class VkPostsController < ApplicationController
  before_action :set_vk_post, only: [:show, :edit, :update, :destroy]

  # GET /vk_posts
  # GET /vk_posts.json
  def index
    @vk_posts = VkPost.all
  end

  # GET /vk_posts/1
  # GET /vk_posts/1.json
  def show
  end

  # GET /vk_posts/new
  def new
    @vk_post = VkPost.new
  end

  # GET /vk_posts/1/edit
  def edit
  end

  # POST /vk_posts
  # POST /vk_posts.json
  def create
    @vk_post = VkPost.new(vk_post_params)

    respond_to do |format|
      if @vk_post.save
        format.html { redirect_to @vk_post, notice: 'Vk post was successfully created.' }
        format.json { render :show, status: :created, location: @vk_post }
      else
        format.html { render :new }
        format.json { render json: @vk_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vk_posts/1
  # PATCH/PUT /vk_posts/1.json
  def update
    respond_to do |format|
      if @vk_post.update(vk_post_params)
        format.html { redirect_to @vk_post, notice: 'Vk post was successfully updated.' }
        format.json { render :show, status: :ok, location: @vk_post }
      else
        format.html { render :edit }
        format.json { render json: @vk_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vk_posts/1
  # DELETE /vk_posts/1.json
  def destroy
    @vk_post.destroy
    respond_to do |format|
      format.html { redirect_to vk_posts_url, notice: 'Vk post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vk_post
      @vk_post = VkPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vk_post_params
      params.require(:vk_post).permit(:post_id, :post_url, :full_text)
    end
end

app/helpers/vk_posts_helper.rb
module VkPostsHelper
end

app/views/vk_posts/_form.html.erb
<%= form_for(@vk_post) do |f| %>
  <% if @vk_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vk_post.errors.count, "error") %> prohibited this vk_post from being saved:</h2>

      <ul>
      <% @vk_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :post_url %><br>
    <%= f.text_area :post_url %>
  </div>
  <div class="field">
    <%= f.label :full_text %><br>
    <%= f.text_area :full_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vk_posts/edit.html.erb
<h1>Editing Vk Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @vk_post %> |
<%= link_to 'Back', vk_posts_path %>

app/views/vk_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vk Posts</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Post url</th>
      <th>Full text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vk_posts.each do |vk_post| %>
      <tr>
        <td><%= vk_post.post_id %></td>
        <td><%= vk_post.post_url %></td>
        <td><%= vk_post.full_text %></td>
        <td><%= link_to 'Show', vk_post %></td>
        <td><%= link_to 'Edit', edit_vk_post_path(vk_post) %></td>
        <td><%= link_to 'Destroy', vk_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vk post', new_vk_post_path %>

app/views/vk_posts/new.html.erb
<h1>New Vk Post</h1>

<%= render 'form' %>

<%= link_to 'Back', vk_posts_path %>

app/views/vk_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @vk_post.post_id %>
</p>

<p>
  <strong>Post url:</strong>
  <%= @vk_post.post_url %>
</p>

<p>
  <strong>Full text:</strong>
  <%= @vk_post.full_text %>
</p>

<%= link_to 'Edit', edit_vk_post_path(@vk_post) %> |
<%= link_to 'Back', vk_posts_path %>